db:
  image: mysql:5.6
  container_name: todo
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: todo
  ports:
  - "3306:3306"