consumes:
- application/io.goswagger.examples.todo-list.v1+json
info:
  description: todo sample application
  title: A Todo list application
  version: 0.1.0
paths: {}
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
swagger: "2.0"
