consumes:
- application/io.goswagger.examples.todo-list.v1+json
definitions:
  todo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
info:
  description: todo sample application
  title: A Todo list application
  version: 0.1.0
paths:
  /todos:
    get:
      tags:
        - todos
      responses:
        200:
          description: list the todos
          schema:
            type: array
            items:
              $ref: "#/definitions/todo"
    post:
      tags:
        - todos
      operationId: addOne
      parameters:
        - name: title
          in: body
          schema:
            $ref: "#/definitions/todo"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/todo"
  /todos/{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    get:
      tags:
        - todos
      responses:
        200:
          description: a single todo
          schema:
            $ref: "#/definitions/todo"
    delete:
      tags:
        - todos
      operationId: destroyOne
      responses:
        204:
          description: Deleted
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
swagger: "2.0"